### ISSUE TITLE
Making the project go gettable

### ISSUE THREAD

**Issue by gernest** [holys/initials-avatar#1]
Hey, kudos for the nice work. It will be great if the project was  easy to install without the make instructions.

That can be easy if the name of the repository would have to change and remove the dash(-) character. I suggest you name it something like `avatar` .

That way, gor people who wants to install  the command it can just type 

``` bash
go get  -v github.com/holys/avatar/cmd/avatar
```

And for those who want to install the library can just type

``` bash
go get  -v github.com/holys/avatar
```

That is ofcourse after moving the contents of  `github.com/holys/initials-avatar/avatar` to `github.com/holys/avatar`

**Comment by holys** [comment]
@gernest  Thanks for your suggestion.  I will add `go get`-able command to Readme.md. 
As for the name, dash will be fine. I just want to distinguish my project from other, like idenicon avatar.

**Comment by gernest** [comment]
@holys That is great.  I will be hacking on the `getInitials`  function [defined here](https://github.com/holys/initials-avatar/blob/dbc8895a13f9a38d53a92aa0c3d590ced1b19049/avatar/avatar.go#L125)

If you don't mind can you explain a little bit about what do you mean by name initials so I can be sure to cover the edge cases? thanks in advance.

**Comment by tjyang** [comment]
Hi All
This my current work around  by adjusting Makefile a bit.
<pre>
-bash-4.3$ cat Makefile
all: get install



get:
        go get -x github.com/dchest/lru
        go get -x github.com/golang/freetype/truetype
        go get -x github.com/labstack/echo
        go get -x golang.org/x/image/font
        go get -x golang.org/x/image/math/fixed
        go get -x stathat.com/c/consistent


install:
        go install -x github.com/holys/initials-avatar/cmd/avatar


-bash-4.3$

</pre>

**Comment by tjyang** [comment]
It will be good  if there is a  simple and complete avatar-hello.go main program got compiled after "make example" command.

**Comment by tjyang** [comment]
FYI, on the subject of make project go gettable, I found this URL http://blog.turret.io/organizing-go-code-to-be-go-gettable/

**Comment by theGeekPirate** [comment]
@gernest If you're going to be modifying getInitials, I recommend looking at grapheme clusters so you handle unicode characters properly. We did a bit of toying around on IRC and found this: https://play.golang.org/p/RMMO7luJvh

Hope that helps!
