### ISSUE TITLE
API to Retrieve Initials From Name

### ISSUE THREAD

**Issue by graywolf336** [holys/initials-avatar#12]
Would be neat to have an api to retrieve the initials used to make the image, that way we can use it for other things.

**Comment by exapsy** [comment]
API? This is a library. Which is used to generate an image. Why would you want this library to have an API to retrieve initials used? This is a business rule, which you can also compute by yourself if you really want to.

```
type Avatar struct {
  Image []byte
  Initials string
}
```

I really dont understand this request. :P
