### ISSUE TITLE
Enhance initials

### ISSUE THREAD

**Issue by holys** [holys/initials-avatar#9]
@gernest   http://gr2m.github.io/initials/  That's what I expect initials to be. If you are interested, you can help improving this feature. :smile:

**Comment by gernest** [comment]
@holys I'm still interested but the link you provided isnt working.

**Comment by holys** [comment]
@gernest  not working？ Try this one: https://github.com/gr2m/initials/

**Comment by gernest** [comment]
@holys thanlks that works. I'm  working on iton it. But you will have to be prepared to test for chinese characters :smile:

**Comment by holys** [comment]
@gernest  OK

**Comment by graywolf336** [comment]
Any update on this? As I'd like to use this and would like to see the features provided via the links above.

**Comment by gernest** [comment]
@graywolf336 I had forgotten about this. If you are going to use it, then let me try to implement it now.

**Comment by graywolf336** [comment]
@gernest That would be awesome! 👍

**Comment by gernest** [comment]
@graywolf336 I have something working. I will add more test tomorrow and submit a PR.

**Comment by graywolf336** [comment]
@gernest Awesome! 👍

**Comment by gernest** [comment]
ping @holys @graywolf336  I tried to make it as simple as possible. I left multiple names feature since it wont align with this project.

And @holys you might want to fix your goveralls setting, it seems the test pass but the goveralls part doesn't.
- Enjoy
